name: Deploy to Skynet

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: cp .env.example .env
      - run: echo SKYNET_CLIENT_SEED='${{ secrets.SKYNET_CLIENT_SEED }}' >> .env
      - run: cat .env
      - run: yarn
      - run: yarn build

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}